name: Test_with_Linter1

on: 
pull_request:
    branches:
      - master
      
  use_linter:
  runs-on: ubuntu-latest
    steps:
    - name: Super-Linter
      uses: github/super-linter@v4.9.7
      
