name: Test_with_Linter

on: [push]
      
jobs:
  Start_and_use_lint: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      
    - name: Super-Linter
      uses: github/super-linter@v4.9.7
